#Travis-Ci
dist: trusty
sudo: required
language: python

python:
- 3.5
- 3.6

branches:
  only:
    - master
    - /^dev\d*[.]?\d*$/

before_install:
  #SWIG & graphviz
  - sudo apt -y install swig graphviz

script:
  - sudo apt -y install desktop-file-utils zenity
  - make
  - python test_pyslvs.py

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
