# Travis-CI for Pyslvs-PyQt5
language: python

matrix:
  include:

    - os: linux
      sudo: required
      python: 3.6
      dist: trusty

    - os: linux
      sudo: required
      python: 3.7
      dist: xenial
      deploy:
        overwrite: true
        provider: releases
        api_key:
          secure: $TRAVIS_TOKEN
        file_glob: true
        file: out/pyslvs*.AppImage
        skip_cleanup: true
        on:
          tags: true

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=37
      deploy:
        overwrite: true
        provider: releases
        api_key:
          secure: $TRAVIS_TOKEN
        file_glob: true
        file: dist/pyslvs*.app
        skip_cleanup: true
        on:
          tags: true

addons:
  apt:
    packages:
      - swig

# For OS X
before_install:

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install swig;
    curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci;
    source ./macports-ci install;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    yes | sudo port install python$PYTHON;
    yes | sudo port install py$PYTHON-pip;
    sudo port select --set python3 python$PYTHON;
    sudo port select --set pip pip$PYTHON;
    pip install pyinstaller --user;
    export PATH=$PATH:$(python3 -c "import site; print(site.USER_BASE)")/bin;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    python3 --version;
    pip --version;
    pyinstaller --version;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    pip install -r requirements.txt --user;
    fi

script:
  - make

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
