name: Python type check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download submodules
        run: git submodule update --init --recursive
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install pip -U
          pip install -r requirements.txt
          pip install mypy
      - name: Install kernel
        working-directory: pyslvs
        run: |
          pip install -r requirements.txt
          python setup.py install
      - name: Lint with mypy
        run: mypy -m launch_pyslvs
